### PR TITLE
added 12-15/28-23 notes

### PR DESCRIPTION
**Pull request by lavender-aa**

### CODE REVIEW

**Comment by paulshriner** [comment]
You need to rebuild the website so the pages will appear on the live version. You can do this by typing the command "hugo" in the terminal. After that you can commit again and it should add to this pull request.

**Comment by lavender-aa** [comment]
i did verify that the new pages showed up on the local port, but even after running hugo again just now (no flags) i'm not able to commit any changes to the two notes files. there were a bunch of other things that i didn't change that appeared; was i supposed to also commit all those?

**Comment by paulshriner** [comment]
That's normal, the md files you add should not change. Hugo uses those to make HTML pages to be displayed using GitHub pages. Were the other files similar to the ones [here](https://github.com/pwsdc/pwsdc.github.io/pull/20/files)? If so then yes those also need to be commited.

**Comment by lavender-aa** [comment]
yeah just a ton of index.html, gotcha. will fix within like a minute, shouldn't take long

**Pull request merged**
