### PR TITLE
added 6-10 notes, adjusted some tags and summaries

### PR DESCRIPTION
**Pull request by lavender-aa**

### CODE REVIEW

**Comment by mwilliams52000** [comment]
"Includes" is misspelled on line 23.

**Comment by paulshriner** [comment]
I think the phrasing on Line 33 could be cleaned up a bit. Something like:

We'll be having a meeting on (**Monday, June 17th** at **7 PM**).

**Comment by lavender-aa** [comment]
personally i see no need to make it as concise as possible

**Comment by mwilliams52000** [comment]
This looks good to me.

**Comment by paulshriner** [comment]
> personally i see no need to make it as concise as possible

My opinion is that it's redundant to say the meeting's on the same day and time, the reader does not need to know that. They just need to know the day and time itself. I think that if you can say something in fewer words while still getting the same point across, you should do so (obviously do not sacrifice clarity just to cut a few words off a sentence). 

I'll leave it up to you if you want to change it or leave it as is. But I think we should consider these points for future meeting notes, I feel like our meeting notes seem like a wall of text (are people actually reading them)?

**Comment by lavender-aa** [comment]
it is my current understanding that most people don't read them, but i'm not really sure what a blog post is if it's not a whole bunch of organized text (and looking back on older posts, they would also be "walls of text," but in my mind that's just what blog posts are)

i think that i'll leave the sentence as is, since it's a stylistic choice (that being of a slightly more conversational tone, though to be far my tone is not the most consistent in these posts) and not an error

**Pull request merged**
